import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Each top-level docs section gets its own autogenerated sidebar, scoped to its
 * directory. The navbar's "Learn" dropdown points at the individual sidebars,
 * so a new section needs an entry here and one in docusaurus.config.ts.
 */
const sidebars: SidebarsConfig = {
  guidedCodingSidebar: [{type: 'autogenerated', dirName: 'guided-coding'}],
  chackSidebar: [{type: 'autogenerated', dirName: 'chack'}],
};

export default sidebars;
